version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: testcase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "32771:5432"